version: '3.7'


services:
  postgres:
        image: postgres:15
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5439:5432'

          
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    environment:
      - DB_HOST=172.19.0.1
    # Run a command against the development stage of the image
    command: >
      bash -c "rm -rf dist &&
               npm run start:dev"
    
    ports:
      - 3000:3000

 

networks:
  default:
    name: postgrest_default
