export const SEQUELIZE = 'SEQUELIZE';
export const BANK_REPOSITORY = 'BANK_REPOSITORY';
export const ACCOUNTS_REPOSITORY = 'ACCOUNTS_REPOSITORY';
export const SUPPLIER_REPOSITORY = 'SUPPLIER_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
